/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit.util;

public final class SemicirclesConverter {
    static final double PI_RADIANS = 0x80000000L;

    static final double CONVERSION_FACTOR = 180.0 / PI_RADIANS;

    public static double semicirclesToDegrees(int semicircles) {
        double degrees = 0.0;

        degrees = semicircles * CONVERSION_FACTOR;

        return degrees;
    }

    public static int degreesToSemicircles(double degrees) {
        int semicircles = 0;

        semicircles = (int) (degrees / CONVERSION_FACTOR);

        return semicircles;
    }
}
