image: maven:3-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_OPTS clean package 

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test

