/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum DisplayOrientation  {
    AUTO((short)0),
    PORTRAIT((short)1),
    LANDSCAPE((short)2),
    PORTRAIT_FLIPPED((short)3),
    LANDSCAPE_FLIPPED((short)4),
    INVALID((short)255);

    protected short value;

    private DisplayOrientation(short value) {
        this.value = value;
    }

    public static DisplayOrientation getByValue(final Short value) {
        for (final DisplayOrientation type : DisplayOrientation.values()) {
            if (value == type.value)
                return type;
        }

        return DisplayOrientation.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( DisplayOrientation value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
