/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum PowerPhaseType  {
    POWER_PHASE_START_ANGLE((short)0),
    POWER_PHASE_END_ANGLE((short)1),
    POWER_PHASE_ARC_LENGTH((short)2),
    POWER_PHASE_CENTER((short)3),
    INVALID((short)255);

    protected short value;

    private PowerPhaseType(short value) {
        this.value = value;
    }

    public static PowerPhaseType getByValue(final Short value) {
        for (final PowerPhaseType type : PowerPhaseType.values()) {
            if (value == type.value)
                return type;
        }

        return PowerPhaseType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( PowerPhaseType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
