/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum RadarThreatLevelType  {
    THREAT_UNKNOWN((short)0),
    THREAT_NONE((short)1),
    THREAT_APPROACHING((short)2),
    THREAT_APPROACHING_FAST((short)3),
    INVALID((short)255);

    protected short value;

    private RadarThreatLevelType(short value) {
        this.value = value;
    }

    public static RadarThreatLevelType getByValue(final Short value) {
        for (final RadarThreatLevelType type : RadarThreatLevelType.values()) {
            if (value == type.value)
                return type;
        }

        return RadarThreatLevelType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( RadarThreatLevelType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
