/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum SegmentDeleteStatus  {
    DO_NOT_DELETE((short)0),
    DELETE_ONE((short)1),
    DELETE_ALL((short)2),
    INVALID((short)255);

    protected short value;

    private SegmentDeleteStatus(short value) {
        this.value = value;
    }

    public static SegmentDeleteStatus getByValue(final Short value) {
        for (final SegmentDeleteStatus type : SegmentDeleteStatus.values()) {
            if (value == type.value)
                return type;
        }

        return SegmentDeleteStatus.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( SegmentDeleteStatus value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
