/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class SportBits4  {
    public static final short SAILING = 0x01;
    public static final short ICE_SKATING = 0x02;
    public static final short SKY_DIVING = 0x04;
    public static final short SNOWSHOEING = 0x08;
    public static final short SNOWMOBILING = 0x10;
    public static final short STAND_UP_PADDLEBOARDING = 0x20;
    public static final short SURFING = 0x40;
    public static final short WAKEBOARDING = 0x80;
    public static final short INVALID = Fit.UINT8Z_INVALID;

    private static final Map<Short, String> stringMap;

    static {
        stringMap = new HashMap<Short, String>();
        stringMap.put(SAILING, "SAILING");
        stringMap.put(ICE_SKATING, "ICE_SKATING");
        stringMap.put(SKY_DIVING, "SKY_DIVING");
        stringMap.put(SNOWSHOEING, "SNOWSHOEING");
        stringMap.put(SNOWMOBILING, "SNOWMOBILING");
        stringMap.put(STAND_UP_PADDLEBOARDING, "STAND_UP_PADDLEBOARDING");
        stringMap.put(SURFING, "SURFING");
        stringMap.put(WAKEBOARDING, "WAKEBOARDING");
    }


    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value, or empty if unknown
     */
    public static String getStringFromValue( Short value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Retrieves a value given a string representation
     * @return The value or INVALID if unkwown
     */
    public static Short getValueFromString( String value ) {
        for( Map.Entry<Short, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
