/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum BpStatus  {
    NO_ERROR((short)0),
    ERROR_INCOMPLETE_DATA((short)1),
    ERROR_NO_MEASUREMENT((short)2),
    ERROR_DATA_OUT_OF_RANGE((short)3),
    ERROR_IRREGULAR_HEART_RATE((short)4),
    INVALID((short)255);

    protected short value;

    private BpStatus(short value) {
        this.value = value;
    }

    public static BpStatus getByValue(final Short value) {
        for (final BpStatus type : BpStatus.values()) {
            if (value == type.value)
                return type;
        }

        return BpStatus.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( BpStatus value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
