/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum Intensity  {
    ACTIVE((short)0),
    REST((short)1),
    WARMUP((short)2),
    COOLDOWN((short)3),
    RECOVERY((short)4),
    INTERVAL((short)5),
    OTHER((short)6),
    INVALID((short)255);

    protected short value;

    private Intensity(short value) {
        this.value = value;
    }

    public static Intensity getByValue(final Short value) {
        for (final Intensity type : Intensity.values()) {
            if (value == type.value)
                return type;
        }

        return Intensity.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( Intensity value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
