/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class LanguageBits1  {
    public static final short DUTCH = 0x01;
    public static final short FINNISH = 0x02;
    public static final short GREEK = 0x04;
    public static final short HUNGARIAN = 0x08;
    public static final short NORWEGIAN = 0x10;
    public static final short POLISH = 0x20;
    public static final short PORTUGUESE = 0x40;
    public static final short SLOVAKIAN = 0x80;
    public static final short INVALID = Fit.UINT8Z_INVALID;

    private static final Map<Short, String> stringMap;

    static {
        stringMap = new HashMap<Short, String>();
        stringMap.put(DUTCH, "DUTCH");
        stringMap.put(FINNISH, "FINNISH");
        stringMap.put(GREEK, "GREEK");
        stringMap.put(HUNGARIAN, "HUNGARIAN");
        stringMap.put(NORWEGIAN, "NORWEGIAN");
        stringMap.put(POLISH, "POLISH");
        stringMap.put(PORTUGUESE, "PORTUGUESE");
        stringMap.put(SLOVAKIAN, "SLOVAKIAN");
    }


    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value, or empty if unknown
     */
    public static String getStringFromValue( Short value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Retrieves a value given a string representation
     * @return The value or INVALID if unkwown
     */
    public static Short getValueFromString( String value ) {
        for( Map.Entry<Short, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
