/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public interface MesgWithEvent {
    public DateTime getTimestamp();
    public void setTimestamp(DateTime timestamp);
    public Event getEvent();
    public void setEvent(Event event);
    public EventType getEventType();
    public void setEventType(EventType type);
    public Short getEventGroup();
    public void setEventGroup(Short group);
}
