/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum SourceType  {
    ANT((short)0),
    ANTPLUS((short)1),
    BLUETOOTH((short)2),
    BLUETOOTH_LOW_ENERGY((short)3),
    WIFI((short)4),
    LOCAL((short)5),
    INVALID((short)255);

    protected short value;

    private SourceType(short value) {
        this.value = value;
    }

    public static SourceType getByValue(final Short value) {
        for (final SourceType type : SourceType.values()) {
            if (value == type.value)
                return type;
        }

        return SourceType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( SourceType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
