/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum StrokeType  {
    NO_EVENT((short)0),
    OTHER((short)1),
    SERVE((short)2),
    FOREHAND((short)3),
    BACKHAND((short)4),
    SMASH((short)5),
    INVALID((short)255);

    protected short value;

    private StrokeType(short value) {
        this.value = value;
    }

    public static StrokeType getByValue(final Short value) {
        for (final StrokeType type : StrokeType.values()) {
            if (value == type.value)
                return type;
        }

        return StrokeType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( StrokeType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
