/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum AutoSyncFrequency  {
    NEVER((short)0),
    OCCASIONALLY((short)1),
    FREQUENT((short)2),
    ONCE_A_DAY((short)3),
    REMOTE((short)4),
    INVALID((short)255);

    protected short value;

    private AutoSyncFrequency(short value) {
        this.value = value;
    }

    public static AutoSyncFrequency getByValue(final Short value) {
        for (final AutoSyncFrequency type : AutoSyncFrequency.values()) {
            if (value == type.value)
                return type;
        }

        return AutoSyncFrequency.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value
     */
    public static String getStringFromValue( AutoSyncFrequency value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
